### ISSUE TITLE
ZDPlasKin Python module

### ISSUE THREAD

**Issue by BangShiuh** [aluque/qtplaskin#1]
Hi,
I would like to know how can build the python module for ZDPlasKin. I found a file called zdplaskin.py, but I don't know how to use it. Do you have any plan to update it? Thank you!

Best,

Bang

**Comment by aluque** [comment]
Dear Bang-Shiuh Chen,

Thank you for your interest in this.  I am writing a message to the ZdPlaskin mail list for the benefit of all other users, in case someone else is interested.

Best regards,

   Alejandro.
