### ISSUE TITLE
error when launching qtplaskin

### ISSUE THREAD

**Issue by rankapino** [aluque/qtplaskin#2]
Hi Alejandro, I'm Fran from InterAmerican University of Puerto Rico.
I'm trying to lunch qtplaskin in Ubuntu (python qtplaskin.py) but I get the following error message 

Traceback (most recent call last):
  File "qtplaskin.py", line 18, in <module>
    from mainwindow import Ui_MainWindow
  File "/home/fran/Documentos/Proyectos/DustDevils/qtplaskin-latest/mainwindow.py", line 365, in <module>
    from mplwidget import RatePlotWidget, SourcePlotWidget, ConditionsPlotWidget, DensityPlotWidget
  File "/home/fran/Documentos/Proyectos/DustDevils/qtplaskin-latest/mplwidget.py", line 13, in <module>
    from matplotlib.backends.backend_qt4agg \
ImportError: cannot import name NavigationToolbar2QTAgg

I have installed all the modules and packages as you recommend

Thanks
best regards

**Comment by aluque** [comment]
Hello, Fran:

This issue was caused by a name change in matplotlib.  I have added a fix but you can also use the fork by E. Pannier which includes this fix and a few additional improvements:

https://github.com/erwanp/qtplaskin

Greetings from Granada,

  Alejandro.
