### ISSUE TITLE
QTplaskin.exe file

### ISSUE THREAD

**Issue by log3441** [aluque/qtplaskin#7]
Hi. I tried to use your project. Thank you for making this.

Firstly I downloaded all (.zip file) and unpressed, but I couldn't find "QTplaskin.exe" file.
There are no execute file in the zip. What do I have to do ?

Thanks !

**Comment by erwanp** [comment]
Hello @log3441 ! 
@aluque 's version indeed had executable files, they're very helpful and hopefully he can answer you on where to find it. 

If you want, you may also use the more recent Fork I co-developed with some other developers : https://github.com/erwanp/qtplaskin 
It has some extra features, however it does not include packaged/executable files (for this reason we never merged it to @aluque 's original version), but it installs in one-line as a Python package. You will need a Python environment installed (Anaconda or any scientific distribution is recommended).

Best,

**Comment by erwanp** [comment]
Btw, any help from other developers in packaging executable files in the new Fork is much welcome. I unfortunately do not have time to dedicate to this project anymore, but the new features/improvements could be useful to users ! See more here #5

**Comment by aluque** [comment]
As @erwanp mentioned, you probably want to use the latest version, which is the one that he maintains now at [https://github.com/erwanp/qtplaskin](https://github.com/erwanp/qtplaskin). In case you really need an executable file for Windows you can find it at [http://trappa.iaa.es/software](http://trappa.iaa.es/software).  However, I do not know how that version works in modern systems.

**Comment by log3441** [comment]
@aluque @erwanp Thank you guys! I solve the problem
also I'll try the things you mentioned. Thank you again for kind answer.
